---
- name: This sets up an httpd webserver
  hosts: 49.254.105.77
  become: yes
  tasks:
  - name: Install the httpd rpm
    yum: name=httpd
  - name: start the httpd service
    service: name=httpd state=started
