---
- name: ontap
  hosts: localhost 
  gather_facts: no
  connection: local
  vars:
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    vserver:  "{{ vserver }}"
    parent_volume: "{{ parent_volume }}"
    vol_name: "{{ vol_name }}"
    snapshot: "{{ snapshot_name }}"

  tasks:
  - name: create SnapShot
    tags:
    - create
      na_ontap_snapshot:
      state: present
      snapshot: "{{ snapshot name }}"
      volume: "{{ parent_volume }}"
      comment: "i am a comment"
      vserver: "{{ vserver name }}"
      username: "{{ netapp username }}"
      password: "{{ netapp password }}"
      hostname: "{{ netapp hostname }}" 
    - name: create volume clone
    na_ontap_volume_clone:
      state: present
      username: "{{ username }}"
      password: "{{ password }}"
      hostname: "{{ hostname }}"
      vserver: "{{ vserver }}"
      parent_volume: "{{ parent_volume }}"
      volume: "{{ vol_name }}"
      parent_snapshot: "{{ snapshot_name }}"   
