---
- hosts: localhost
  gather_facts: false 
  name: ontap snapmirror 
  tasks: 
  - name: Remove SnapMirror
    na_ontap_snapmirror: 
      state: absent 
      source_hostname: "{{ source_hostname }}"
      destination_path: svm_CVO:ansible_target
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
