---
- name: ontap
  hosts: localhost 
  gather_facts: no
  connection: local
  tasks:
  - name: Create FlexVol
    na_ontap_volume:
      state: present
      name: "{{ vol_name }}"
      vserver: "{{ vserver }}"
      type: RW 
      junction_path: "/{{ vol_name }}"
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
