---
- name: ontap
  hosts: localhost 
  gather_facts: no
  connection: local
  tasks:
  - name: Change RW
    na_ontap_volume:
      name: "{{ vol_name }}"
      vserver: "{{ vserver }}"
      policy: default 
      type: RW 
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"

- hosts: netapp
  gather_facts: no
  tasks:
    - name: Set Junction Path
      raw: volume mount -vserver svm_CVO -volume yj_ansi01_copy -junction-path /yj_ansi01_copy
